### ISSUE TITLE
Emails Refresh

### ISSUE THREAD

**Issue by sanzeeb3** [sanzeeb3/wp-frontend-delete-account#10]
A filter (or an option in the settings) would be great.

Request: https://wordpress.org/support/topic/from-email-address-16/

Extract:

> I would like set the ‘From email’ only for the delete account notifications by WP Frontend Delete Account plugin and maintain the ‘from email’ I have set as it is for other plugins.

**Comment by pickmeok** [comment]
Hi Sanzeeb,

This code seems to work without changing other 'from email' addresses.
Is it possible to change the 'From name' of info@example.com email address?

Thank you



function wpfda_sender_email( $email ) {
    return 'info@example.com';
}
add_filter( 'wp_mail_from', 'wpfda_sender_email' );

**Comment by sanzeeb3** [comment]
Add all these options one day:

![Screenshot on 2021-02-09 at 14_16_08](https://user-images.githubusercontent.com/16817248/107336694-8070e400-6ae1-11eb-9fa6-0670955d339c.png)

**Comment by sanzeeb3** [comment]
Addressed in d09f6904ec731bc8b747c9144a88d4e34d54f742 and ef162beda8ff5251bb31c1275b0cfd77db8b652a
