### ISSUE TITLE
"Confirm" button not translatable

### ISSUE THREAD

**Issue by chverdin** [sanzeeb3/wp-frontend-delete-account#57]
The "Confirm" button cannot be translated on the frontend with WPML.

In functions.php (v1.6.1), I needed to update line 60:
'button'              => get_option( 'wpfda_button_label', 'Confirm' ),
with:
'button'              => get_option( 'wpfda_button_label', esc_html__( 'Confirm', 'wp-frontend-delete-account' ) ),

Thanks you!

**Comment by sanzeeb3** [comment]
@chverdin this should be fixed but it's a little tricky. It can no more be translated once the settings is saved.

@neetikaaryal can you please create a PR for this?

**Comment by neetikaaryal** [comment]
Done! Hope it solves the issue.
