### ISSUE TITLE
Feature Request: Would it be possible to restrict to Customer Accounts

### ISSUE THREAD

**Issue by MikeWilliams-UK** [sanzeeb3/wp-frontend-delete-account#74]
I have installed this plug in and I am now getting the Delete Account link under the WooCommerce my-account page.

Could you please add an option to ONLY show the Delete Account for WordPress accounts which have the Role of "Customer"

**Comment by sanzeeb3** [comment]
An option to exclude specific user roles.

**Comment by sanzeeb3** [comment]
Available in PRO version 2.0.0

**Comment by MikeWilliams-UK** [comment]
That's not fair, putting such an important safety feature behind a paywall.
